version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: ucode_race01_node
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - ucode_race01

  db:
    image: mysql:8.0
    container_name: ucode_race01_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ucode_race01

volumes:
  mysql_data:

networks:
  ucode_race01:
